development: &default
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  encoding: utf8
  reconnect: true
  password: <%= ENV['DB_PASS'] %>
  port: <%= ENV['DB_PORT'] %>

test:
  adapter: mysql2
  database: 'test_tocat'
  host: localhost
  username: root
  encoding: utf8
  reconnect: true
  password: ''
  port: 3306

production:
  <<: *default
