development: &default
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  encoding: utf8
  reconnect: true
  password: <%= ENV['DB_PASS'] %>
  port: <%= ENV['DB_PORT'] %>

test:
  <<: *default
production:
  <<: *default
