development: &default
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_TOKEN_BASE'] %>
  shiftplanning_key: <%= ENV['SHIFTPLANNING_KEY'] %>
  shiftplanning_login: <%= ENV['SHIFTPLANNING_LOGIN'] %> 
  shiftplanning_password: <%= ENV['SHIFTPLANNING_PASSWORD'] %> 

test:
  <<: *default
production:
  <<: *default
