development: &default
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: testtest
  shiftplanning_key: <%= ENV['SHIFTPLANNING_KEY'] %>
  shiftplanning_login: <%= ENV['SHIFTPLANNING_LOGIN'] %> 
  shiftplanning_password: <%= ENV['SHIFTPLANNING_PASSWORD'] %> 
  tocat_manager: <%= ENV['TOCAT_OWNER'] %>

test:
  <<: *default
production:
  <<: *default
