---
chdir: "/srv/tocat"
environment: <% ENV['RAILS_ENV'] %>
socket: /tmp/thin.sock
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 1024
require: []
wait: 30
